# Generated by Django 4.1.6 on 2023-02-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default=44600, max_length=255),
            preserve_default=False,
        ),
    ]
