# Generated by Django 4.1.6 on 2023-02-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_address_zip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
